name: Tuya2Matter
version: "1.0.62"
slug: tuya2matter
description: |
  Bridge Tuya devices into Matter using Bun.js.

  ğŸ‘‰ Instructions: Set USER_CODE and check log for qrcode
  
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
ingress: false

# Quan trá»ng: báº­t host network Ä‘á»ƒ mDNS hoáº¡t Ä‘á»™ng
host_network: true

map:
  - config:rw
  - share:rw
  - media:rw
  - ssl:ro

schema:
  user_code: str?
  tuya2mqtt_debug: str?
options:
  user_code: ""
  tuya2mqtt_debug: ""